def hanging_post(number_of_errors):
    if number_of_errors == 0:
        print('    ---------------¬')
        print('    |              *')
        print('    |              *')
        print('    |')
        print('    |')
        print('    |')
        print('    |')
        print('    |')
        print('    |')
        print(' -------')
    elif number_of_errors == 1:
        print('    ---------------¬')
        print('    |              *')
        print('    |              *')
        print('    |              O')
        print('    |')
        print('    |')
        print('    |')
        print('    |')
        print('    |')
        print(' -------')
    elif number_of_errors == 2:
        print('    ---------------¬')
        print('    |              *')
        print('    |              *')
        print('    |              O')
        print('    |              |')
        print('    |              |')
        print('    |')
        print('    |')
        print('    |')
        print(' -------')
    elif number_of_errors == 3:
        print('    ---------------¬')
        print('    |              *')
        print('    |              *')
        print('    |              O')
        print('    |              |')
        print('    |              |')
        print('    |             /')
        print('    |            /')
        print('    |')
        print(' -------')
    elif number_of_errors == 4:
        print('    ---------------¬')
        print('    |              *')
        print('    |              *')
        print('    |              O')
        print('    |              |')
        print('    |              |')
        print('    |             / \\')
        print('    |            /   \\')
        print('    |')
        print(' -------')
    elif number_of_errors == 5:
        print('    ---------------¬')
        print('    |              *')
        print('    |              *')
        print('    |              O')
        print('    |             /|')
        print('    |            / |')
        print('    |             / \\')
        print('    |            /   \\')
        print('    |')
        print(' -------')
    elif number_of_errors == 6:
        print('    ---------------¬')
        print('    |              *')
        print('    |              *')
        print('    |              O')
        print('    |             /|\\')
        print('    |            / | \\')
        print('    |             / \\')
        print('    |            /   \\')
        print('    |')
        print(' -------')